Repository pymc-devs/pymc-extras, pull requests merged in 2023-04, with the labels that each got.

#136 Remove HSGP as it became a part of PyMC
  pymc_experimental/gp/__init__.py
  pymc_experimental/gp/latent_approx.py
Labels: major

#100 add DiscreteMarkovChainRV
  docs/api_reference.rst
  notebooks/discrete_markov_chain.ipynb
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/timeseries.py
  pymc_experimental/tests/distributions/test_discrete_markov_chain.py
Labels: enhancements

#115 Tweak README.md
  README.md
Labels: docs, no releasenotes

#157 Add codecov badge to Readme
  README.md
Labels: docs
