Repository pymc-devs/pymc-extras, pull requests merged in 2023-12, with the labels that each got.

#284 Fix testing and remove warnings for r2d2m2cp
  pymc_experimental/distributions/multivariate/r2d2m2cp.py
  pymc_experimental/tests/distributions/test_multivariate.py
Labels: maintenance, no releasenotes

#287 Bugfixes for `statespace/models/structural.py`
  docs/statespace/models.rst
  docs/statespace/models/structural.rst
  pymc_experimental/__init__.py
  pymc_experimental/statespace/core/statespace.py
  pymc_experimental/statespace/filters/distributions.py
  pymc_experimental/statespace/models/structural.py
  pymc_experimental/tests/statespace/test_data/airpassangers.csv
  pymc_experimental/tests/statespace/test_structural.py
  pymc_experimental/tests/statespace/utilities/test_helpers.py
Labels: bug

#288 Fix initial state size in CycleComponent
  pymc_experimental/statespace/models/structural.py
  pymc_experimental/tests/statespace/test_structural.py
Labels: bug

#285 Implement utility to recover marginalized variables from `MarginalModel`
  pymc_experimental/model/marginal_model.py
  pymc_experimental/tests/model/test_marginal_model.py
Labels: enhancements
