Repository pymc-devs/pymc-extras, pull requests merged in 2023-11, with the labels that each got.

#256 Bump version
  pymc_experimental/version.txt
Labels: no releasenotes

#260 Implement Skellam distribution
  docs/api_reference.rst
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/discrete.py
  pymc_experimental/tests/distributions/test_discrete.py
Labels: enhancements

#258 Implement BetaNegativeBinomial distribution
  docs/api_reference.rst
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/discrete.py
  pymc_experimental/tests/distributions/test_discrete.py
Labels: enhancements

#261 Implement Maxwell Distribution
  docs/api_reference.rst
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/continuous.py
  pymc_experimental/tests/distributions/test_continuous.py
Labels: enhancements

#249 Set data when building Linearmodel
  pymc_experimental/linearmodel.py
  pymc_experimental/model_builder.py
  pymc_experimental/tests/test_linearmodel.py
  pymc_experimental/tests/test_model_builder.py
Labels: bug

#267 Blackjax SMC from pymc models
  conda-envs/windows-environment-test.yml
  pymc_experimental/inference/smc/__init__.py
  pymc_experimental/inference/smc/sampling.py
  pymc_experimental/tests/test_blackjax_smc.py
Labels: enhancements

#268 Add `@as_model` decorator
  docs/api_reference.rst
  pymc_experimental/__init__.py
  pymc_experimental/model/__init__.py
  pymc_experimental/model/marginal_model.py
  pymc_experimental/model/model_api.py
  pymc_experimental/tests/model/__init__.py
  pymc_experimental/tests/model/test_marginal_model.py
  pymc_experimental/tests/model/test_model_api.py
Labels: enhancements

#270 Bump version to 0.0.14
  pymc_experimental/version.txt
Labels: no releasenotes

#272 Adapt PyMC 5.10.0 breaking changes
  conda-envs/environment-test.yml
  conda-envs/windows-environment-test.yml
  pymc_experimental/model/marginal_model.py
  pymc_experimental/utils/prior.py
  requirements.txt
Labels: maintenance, no releasenotes
