Repository pymc-devs/pymc-extras, pull requests merged in 2023-06, with the labels that each got.

#183 Bump PyMC dependency
  conda-envs/environment-test.yml
  conda-envs/windows-environment-test.yml
  pymc_experimental/marginal_model.py
  requirements.txt
  setup.py
Labels: maintenance, no releasenotes

#185 Pass kwargs through to pymc sample calls
  pymc_experimental/model_builder.py
  pymc_experimental/tests/test_linearmodel.py
Labels: maintenance

#186 Bump version for release
  pymc_experimental/version.txt
Labels: no releasenotes

#187 Bump version ++
  pymc_experimental/version.txt
Labels: no releasenotes

#191 Update to pymc 5.5.0
  pymc_experimental/distributions/timeseries.py
  pymc_experimental/marginal_model.py
  requirements.txt
Labels: maintenance
