Repository pymc-devs/pymc-extras, pull requests merged in 2023-05, with the labels that each got.

#143 Add Generalized Poisson distribution
  docs/api_reference.rst
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/discrete.py
  pymc_experimental/tests/distributions/test_discrete.py
Labels: enhancements

#137 Add r2m2d2cp prior
  docs/api_reference.rst
  pymc_experimental/distributions/__init__.py
  pymc_experimental/distributions/histogram_utils.py
  pymc_experimental/distributions/multivariate/__init__.py
  pymc_experimental/distributions/multivariate/r2d2m2cp.py
  pymc_experimental/tests/distributions/test_multivariate.py
  pyproject.toml
Labels: enhancements

#165 Merging BayesianEstimator into ModelBuilder
  pymc_experimental/bayesian_estimator_linearmodel.py
  pymc_experimental/linearmodel.py
  pymc_experimental/model_builder.py
  pymc_experimental/tests/test_linearmodel.py
  pymc_experimental/tests/test_model_builder.py
  pytest.ini
Labels: enhancements, request discussion

#180 Fix docstrings code-block
  pymc_experimental/utils/model_fgraph.py
Labels: docs, no releasenotes
