Repository pymc-devs/pymc-extras, pull requests merged in 2024-12, with the labels that each got.

#385 Add `find_MAP` with close JAX integration and fix bug with Laplace fit
  conda-envs/environment-test.yml
  conda-envs/windows-environment-test.yml
  pymc_experimental/inference/find_map.py
  pymc_experimental/inference/fit.py
  pymc_experimental/inference/laplace.py
  tests/statespace/test_ETS.py
  tests/test_find_map.py
  tests/test_laplace.py
Labels: enhancements

#399 Remove the duplicate pre-commit job
  .github/workflows/pre-commit.yml
Labels: maintenance, no releasenotes

#405 pymc-extras first release (v0.2)
  README.md
  pymc_extras/version.txt
Labels: no releasenotes, release
