Repository pymc-devs/pymc-extras, pull requests merged in 2024-02, with the labels that each got.

#304 Fix MarginalModel with Data containers
  pymc_experimental/model/marginal_model.py
  pymc_experimental/tests/model/test_marginal_model.py
Labels: bug, marginalization

#307 Fix JAX warnings in tests
  pyproject.toml
Labels: maintenance, no releasenotes, tests

#302 Statespace: Don't automatically save statespace matrices as `Deterministic` variables
  pymc_experimental/statespace/core/representation.py
  pymc_experimental/statespace/core/statespace.py
  pymc_experimental/statespace/filters/distributions.py
  pymc_experimental/statespace/filters/kalman_filter.py
  pymc_experimental/statespace/filters/kalman_smoother.py
  pymc_experimental/statespace/models/SARIMAX.py
  pymc_experimental/statespace/models/VARMAX.py
  pymc_experimental/statespace/models/structural.py
  pymc_experimental/statespace/models/utilities.py
  pymc_experimental/tests/statespace/test_SARIMAX.py
  pymc_experimental/tests/statespace/test_VARMAX.py
  pymc_experimental/tests/statespace/test_coord_assignment.py
  pymc_experimental/tests/statespace/test_distributions.py
  pymc_experimental/tests/statespace/test_statespace.py
  pymc_experimental/tests/statespace/test_structural.py
  pymc_experimental/tests/statespace/utilities/test_helpers.py
Labels: enhancements, major, statespace

#257 Support HMM via marginalization of DiscreteMarkovChain
  pymc_experimental/model/marginal_model.py
  pymc_experimental/tests/model/test_marginal_model.py
Labels: enhancements, marginalization
