Repository pymc-devs/pymc-extras, pull requests merged in 2025-06, with the labels that each got.

#515 Use `hermitian=True` in `pt.linalg.pinv` in Kalman smoother
  pymc_extras/statespace/filters/kalman_smoother.py
Labels: maintenance, statespace

#519 Add `BaseEstimator` mixin to `LinearModel`
  pymc_extras/linearmodel.py
Labels: maintenance

#523 Correct prior doc method name
  pymc_extras/prior.py
Labels: docs
