Repository pymc-devs/pymc-extras, pull requests merged in 2025-01, with the labels that each got.

#388 Implement marginalization as a model transformation and deprecate MarginalModel
  README.md
  docs/api_reference.rst
  pymc_extras/__init__.py
  pymc_extras/distributions/timeseries.py
  pymc_extras/model/marginal/distributions.py
  pymc_extras/model/marginal/graph_analysis.py
  pymc_extras/model/marginal/marginal_model.py
  pymc_extras/utils/model_equivalence.py
  tests/model/marginal/test_distributions.py
  tests/model/marginal/test_marginal_model.py
  tests/test_pivoted_cholesky.py
  tests/utils.py
Labels: maintenance, major, marginalization

#408 Update version.txt
  pymc_extras/version.txt
Labels: release

#413 Check model coords for unknown shapes when building predictive models
  pymc_extras/statespace/core/statespace.py
  tests/statespace/test_statespace.py
Labels: bug, statespace

#414 `as_model` wraps function arguments in `Data` if they support it.
  pymc_extras/model/model_api.py
  tests/model/test_model_api.py
Labels: maintenance

#387 PyMC/PyTensor Implementation of Pathfinder VI
  pymc_extras/inference/fit.py
  pymc_extras/inference/pathfinder.py
  pymc_extras/inference/pathfinder/__init__.py
  pymc_extras/inference/pathfinder/importance_sampling.py
  pymc_extras/inference/pathfinder/lbfgs.py
  pymc_extras/inference/pathfinder/pathfinder.py
  tests/test_pathfinder.py
Labels: enhancements
